name: 'Zenodo New Version'
description: 'Creates a new version of the provided Zenodo deposition'
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  zenodo_deposition_id:
    description: 'The ID of the Zenodo Deposition to create a new version of.'
    required: true
  zenodo_server:
    description: 'The URL of the Zenodo Server to use, set "https://zenodo.org" for production'
    required: false
    default: 'https://sandbox.zenodo.org'
  zenodo_token:
    description: 'The Auth Token for Zenodo'
    required: true
outputs:
  latest_doi:
    description: "DOI of the latest deposition"
    value: ${{ steps.retrieve_dois.outputs.latest_doi}}
  reserved_doi:
    description: "Reserved DOI of the new draft"
    value: ${{ steps.retrieve_dois.outputs.reserved_doi}}
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install zenodo-rest
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install zenodo-rest==0.0.0b9
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch Latest Deposition
      shell: bash
      env:
        ZENODO_TOKEN: ${{ inputs.zenodo_token }}
        ZENODO_URL: ${{ inputs.zenodo_server }}
      run: |
        zenodo-rest depositions retrieve ${{ inputs.zenodo_deposition_id }} --dest .tmp_zenodo_deposition.json
    - name: Create new version 
      shell: bash
      env:
        ZENODO_TOKEN: ${{ inputs.zenodo_token }}
        ZENODO_URL: ${{ inputs.zenodo_server }}
      run: |
        # Create new version
        cat .tmp_zenodo_deposition.json
        zenodo-rest depositions new-version .tmp_zenodo_deposition.json --dest .tmp_zenodo_deposition.json
        
    - name: Retrieve DOIs of latest deposition and new draft
      id: retrieve_dois
      shell: bash
      env:
        ZENODO_TOKEN: ${{ inputs.zenodo_token }}
        ZENODO_URL: ${{ inputs.zenodo_server }}
      run: |
        LATEST_DOI=$(zenodo-rest depositions doi latest .tmp_zenodo_deposition.json)
        echo "::set-output name=latest_doi::$LATEST_DOI"
        RESERVED_DOI=$(zenodo-rest depositions doi latest-draft .tmp_zenodo_deposition.json)
        echo "::set-output name=reserved_doi::$RESERVED_DOI"
